### ISSUE TITLE
db: failed to load data: quad exists

### ISSUE THREAD

**Issue by ZhengYang** [google/cayley#285]
Hi, I was trying to load data from this link: http://tools.wmflabs.org/wikidata-exports/rdf/exports/20150713/wikidata-simple-statements.nt.gz
using command:
```
./cayley repl -dbpath=/wikidata-simple-statements.nt
```
I get this error:
```
E0726 17:46:41.652479 81324 cayley.go:251] db: failed to load data: quad exists
```
Any hints what did I do wrongly?
I'm using `cayley_0.4.1_darwin_386` build.

**Comment by kortschak** [comment]
Pass the `-ignoredup` flag when you invoke cayley during the load.

https://github.com/google/cayley/blob/master/graph/quadwriter.go#L67

**Comment by ZhengYang** [comment]
That worked. Thanks!

**Comment by droidresearch** [comment]
It works in Windows. However in mac it gives "flag provided but not defined: -ignoredup"
any suggestions?

**Comment by droidresearch** [comment]
The workaround I am using in mac is 
sort testdata.nq | uniq > uniqtestdata.nq
and then use uniqtestdata.nq for loading.

**Comment by kortschak** [comment]
Are you sure The version you have built for mac has that option? What does "cayley -help" print? What is the sha for the source you used?

**Comment by droidresearch** [comment]
I have not built the cayley from the source. I have just downloaded the release binary for https://github.com/google/cayley/releases/download/v0.3.1/cayley_0.3.1_darwin_amd64.zip

PFB, the cayley help
flag provided but not defined: -ignoredup
Usage of ./cayley:
  -alsologtostderr=false: log to standard error as well as files
  -assets="": Explicit path to the HTTP assets.
  -config="": Path to an explicit configuration file.
  -db="memstore": Database Backend.
  -dbpath="/tmp/testdb": Path to the database.
  -gremlin_timeout=30: Number of seconds until an individual query times out.
  -host="0.0.0.0": Host to listen on (defaults to all).
  -load_size=10000: Size of triplesets to load
  -log_backtrace_at=:0: when logging hits line file:N, emit a stack trace
  -log_dir="": If non-empty, write log files in this directory
  -logstashtype="": enable logstash logging and define the type
  -logstashurl="172.17.42.1:5042": logstash url and port
  -logtostderr=false: log to standard error instead of files
  -port="64210": Port to listen on.
  -prof="": Output profiling file.
  -query_lang="gremlin": Use this parser as the query language.
  -read_only=false: Disable writing via HTTP.
  -stderrthreshold=0: logs at or above this threshold go to stderr
  -triples="": Triple File to load before going to REPL.
  -v=0: log level for V logs
  -vmodule=: comma-separated list of pattern=N settings for file-filtered logging

**Comment by kortschak** [comment]
The dup handling options are not in that version, please try 0.4.1.

**Comment by ZChristine** [comment]
I import nq file(11666KB) with the command prompt " ./cayley http -i ./data/30kmoviedata.nq.gz -d elastic -a http://localhost:9200 --host=:64210 " in 45h17m13.8236902s. I wonder why it takes so long? is it because the size of the file?
