### ISSUE TITLE
Concurrent writing to memstore results in panic

### ISSUE THREAD

**Issue by josephschorr** [google/cayley#318]
The exception usually occurs while trying to write a Quad. In this example, `GOMAXPROCS=4` on a dual core machine.

One example trace:

```
fatal error: bad map state

goroutine 48 [running]:
runtime.gothrow(0x4a3910, 0xd)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/panic.go:503 +0x8e fp=0xc20817f230 sp=0xc20817f218
runtime.evacuate(0x3364c0, 0xc2081344b0, 0x5)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/hashmap.go:799 +0x36a fp=0xc20817f2f0 sp=0xc20817f230
runtime.growWork(0x3364c0, 0xc2081344b0, 0x8)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/hashmap.go:769 +0x8a fp=0xc20817f310 sp=0xc20817f2f0
runtime.mapassign1(0x3364c0, 0xc2081344b0, 0xc20817f428, 0xc208183860)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/hashmap.go:408 +0x18f fp=0xc20817f3b0 sp=0xc20817f310
github.com/google/cayley/graph/memstore.(*QuadStore).AddDelta(0xc208183860, 0x1, 0x0, 0x41, 0x0, 0x0, 0xc208130210, 0x24, 0x4aac10, 0x9, ...)
	/go/src/github.com/google/cayley/graph/memstore/quadstore.go:186 +0x3ab fp=0xc20817f4f0 sp=0xc20817f3b0
github.com/google/cayley/graph/memstore.(*QuadStore).ApplyDeltas(0xc208183860, 0xc208160510, 0x1, 0x1, 0x0, 0x0, 0x0)
	/go/src/github.com/google/cayley/graph/memstore/quadstore.go:113 +0x1ec fp=0xc20817f720 sp=0xc20817f4f0
github.com/google/cayley/writer.(*Single).AddQuad(0xc2080e7240, 0xc208130210, 0x24, 0x4aac10, 0x9, 0xc2081345d0, 0x24, 0x48edf0, 0x3, 0x0, ...)
	/go/src/github.com/google/cayley/writer/single.go:77 +0x1bb fp=0xc20817f850 sp=0xc20817f720
```

Another trace:

```
panic: runtime error: index out of range

goroutine 19 [running]:
github.com/google/cayley/graph/memstore.(*Iterator).Next(0xc20809a4d0, 0x0)
	/go/src/github.com/google/cayley/graph/memstore/iterator.go:126 +0x3bf
github.com/google/cayley/graph/memstore.(*QuadStore).indexOf(0xc2080ba060, 0xc208065140, 0x24, 0xc208062f00, 0xd, 0xc208062ef2, 0xe, 0x48edf0, 0x3, 0xc20808c900, ...)
	/go/src/github.com/google/cayley/graph/memstore/quadstore.go:158 +0x104
github.com/google/cayley/graph/memstore.(*QuadStore).AddDelta(0xc2080ba060, 0x1, 0x0, 0x46, 0x0, 0x0, 0xc208065140, 0x24, 0xc208062f00, 0xd, ...)
	/go/src/github.com/google/cayley/graph/memstore/quadstore.go:168 +0x63
github.com/google/cayley/graph/memstore.(*QuadStore).ApplyDeltas(0xc2080ba060, 0xc208149050, 0x1, 0x1, 0x0, 0x0, 0x0)
	/go/src/github.com/google/cayley/graph/memstore/quadstore.go:113 +0x1ec
github.com/google/cayley/writer.(*Single).AddQuad(0xc208134000, 0xc208065140, 0x24, 0xc208062f00, 0xd, 0xc208062ef2, 0xe, 0x48edf0, 0x3, 0x0, ...)
	/go/src/github.com/google/cayley/writer/single.go:77 +0x1bb
```

**Comment by kortschak** [comment]
Would you provide a complete reproducer please.

**Comment by josephschorr** [comment]
Reproducer:

```
package main

import (
	"fmt"
	"sync"

	"github.com/google/cayley"
)

func main() {
	store, _ := cayley.NewMemoryGraph()

	runner := func(index int, wg *sync.WaitGroup) {
		for i := 0; i < 1000; i++ {
			store.AddQuad(cayley.Quad("subject", fmt.Sprintf("predicate-%v", i), fmt.Sprintf("object-%v", i), ""))
		}

		wg.Done()
	}

	wg := sync.WaitGroup{}

	for i := 0; i < 10; i++ {
		wg.Add(1)
		go runner(i, &wg)
	}

	wg.Wait()
}
```

run with `GOMAXPROCS=4` and it panics

**Comment by kortschak** [comment]
OK. That is expected behaviour; you are breaking the client side of the contract. memstore.QuadStore is not marked as safe for concurrent use (admittedly it's not documented at all, but that's another matter); and it's built on things that are specifically noted as not being safe for concurrent writes (go maps and cznic/b B-trees). If you want to make concurrent write (more later), you will need to add synchronisation.

The reason there is no concurrency safety on this type is that there is no benefit. Every write needs to be synchronised since they all end up in the same store, and reads also need to be synchronised with the writes. This means that you actually get no benefit.

*If* you are seeing memstore writes being a significant bottleneck (I doubt it), *and* you know how your graph segments before hand, then you can just store into separate stores for each segment. Otherwise, there is really not much to do here.

**Comment by josephschorr** [comment]
Not being concurrently safe is perfectly fine (although unexpected, given the lack of documentation). Should I submit a PR to add such a warning to the memstore documentation?

In regards to why the underlying store is not concurrently safe, I certainly understand that it is built on primitives that would preclude that safety without work to add locking.  I don't agree, however, that there isn't value in doing so: If concurrently safe, I could confidently write multiple values while reading values I know to be present from previous phases of my program. If I were using a relational DB, I expect that my reads and writes can occur concurrently, even if I have to manually handle read-after-write hazards and the like myself. Granted, Cayley is a different beast, but it was certainly odd to encounter this restriction.

Incidentally, does the Bolt driver suffer the same limitation? I'd love to have the speed of an in-memory graph, but with concurrency guarantees. If not, I'll add my own locking in my own wrapper code, but have no desire to implement unless required.

**Comment by kortschak** [comment]
No warning is needed for memstore, though docs are needed - there is #94 for this. The basis for this is that Go types by convention are not safe for concurrent use unless marked otherwise.

The rationale for not adding synchronisation to types by default is that in the non-concurrent case those additions add significant cost and the cost of adding synchronisation to the external access is not onerous. If your runner func added a sync.RWMutex then you would have what you want. The convention is a language wide-one, not specific to cayley.

I don't know how to bolt driver works, but looking at it I would say it depends entirely on whether bold.Tx are concurrency safe. The [bolt docs say](https://github.com/boltdb/bolt#transactions) that between Tx concurrency use is safe - i.e. a Tx is not safe, but two independent Tx in different goroutines is fine.

**Comment by josephschorr** [comment]
Makes sense. Thanks for the information and hopefully the docs issue will make this more clear to other users in the future. Closing this issue.

**Comment by mzimmerman** [comment]
Indeed, I cannot use concurrent writing to boltdb either as the race detector flags this.  In my case, I pre-process GBs of data and then I need to load it for visualization and querying.  As the code in my pre-process changes a lot, maximizing ingest speed is important.

Prior to attempting to use Cayley I was using maps pointing to slices to make my many-to-many relationships work out and I sharded the data to get concurrency.

**Comment by josephschorr** [comment]
@mzimmerman: I ended up creating a small lib for all write operations on my underlying memstore-backed Cayley graph: https://github.com/Serulian/compiler/blob/master/compilergraph/modifier.go. I can scan my graph in parallel (since it is read-only) and "change" it in parallel, while only applying the changes themselves transactionally once I'm done. Seems to have worked so far! :)

**Comment by dennwc** [comment]
@mzimmerman Fixed bolt in 18f310ff0788fc2a494a6dd1db71d45f6c876610. Someone missed concurrent modification of cached size variables.

Memstore is still unsafe for concurrent modification, as it was.

**Comment by mzimmerman** [comment]
Wow, awesome!  I'll try this on Monday, thanks.

**Comment by mzimmerman** [comment]
Forgive me for continuing to dig up this old bug!

@dennwc When I use your fix, there's no race condition anymore, however the performance isn't parallel in that overall CPU usage barely gets over one core.  I do see that bolt supports *some* parallel operations on write although exactly what performance one could expect I'm not sure.

https://github.com/boltdb/bolt#batch-read-write-transactions

Cayley seems not to use the .Batch() function however.  Is that a possibility?  I admit that I don't understand the internals to dig into it further.

**Comment by dennwc** [comment]
@mzimmerman No we are not using batch for now. But we are working on a new Bolt-based backend which is already much faster. Later we will add a batch mode for initial import of the database, it will omit building most indexes until it has all quads, and then will run reindex in parallel.
